### ISSUE TITLE
Move region string to parameter of script

### ISSUE THREAD

**Issue by bmorrissirromb** [aws-samples/aws-iam-identity-center-scim-sync#1]
Users should not have to change the script in order for it to meet their needs.

**Comment by meduncan** [comment]
Reviewed the CloudFormation and PS script to make corrections to remove hard coded us-east-2 dependencies.  Performing testing now to validate changes before publishing.

**Comment by meduncan** [comment]
Made changes to the PS script and CloudFormation template to remove the hard coded region dependencies.  The solution should now be deployable in any region that supports the AWS services used.
